/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eerrhefkzgtmaryevbvp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlcnJoZWZremd0bWFyeWV2YnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2Mzk0OTgsImV4cCI6MjEwMjIxNTQ5OH0.pADUwSBsjG4lQ7J1R59kf-f-Gn3ehgvFlCdbRhVG76c"